### ISSUE TITLE
Limiter threshold and release controls do nothing

### ISSUE THREAD

**Issue by acarasimon96** [Audio4Linux/JDSP4Linux#12]
Recently, I discovered that changing sliders for limiter threshold and release time have no effect to the output. If they did work, I would expect the sound to become quieter or compressed. The post-gain slider adjusts the volume of the processed audio as expected, however.

**App version:** 2.2 (PulseAudio build installed from [AUR](https://aur.archlinux.org/packages/jamesdsp-pulse))
**JamesDSP core version:** 4.1.0
**PulseAudio version:** 15.0.0
**Distribution:** Manjaro

**Comment by ThePBone** [comment]
Thanks for the report.

It looks like I accidentally switched the `lim_release` and `lim_threshold` keys up when rewriting some code. :sweat_smile: 

Due to boundary checks, both properties were reset to their default value since they were entirely out-of-bounds (caused by the switched-up properties).

Anyway, commit 8a6de152ba8fbf25382ba8ff2162f225c78a755b fixes this issue.
