### ISSUE TITLE
using nl80211

### ISSUE THREAD

**Issue by s-rs** [Audio4Linux/JDSP4Linux#129]
[   20.336769] warning: `jamesdsp' uses wireless extensions which will stop working for Wi-Fi 7 hardware; use nl80211

this error pops up in kernel logs

**Comment by ThePBone** [comment]
This warning appears to be caused by Qt (UI toolkit) and not by JamesDSP itself.
JDSP doesn't use wireless extensions, so this is a Qt bug. 
See also here: https://github.com/nextcloud/desktop/issues/5646#issuecomment-1579354538

[QTBUG-114336](https://bugreports.qt.io/browse/QTBUG-114336) has been filed, it will probably be fixed in a future Qt update.

**Comment by s-rs** [comment]
alright, thanks for your work
