### ISSUE TITLE
Binary release for Ach ? Or an Appimage release ?

### ISSUE THREAD

**Issue by medmedin2014** [Audio4Linux/JDSP4Linux#130]
The installation process is really long, I waited more than 25min and the compiling is not finished yet, is there any binary or Appimage release ready to install ?

![Screenshot_20230623_122608](https://github.com/Audio4Linux/JDSP4Linux/assets/7027319/e129a7da-4ba0-476c-833b-0272eeb18bc4)

**Comment by ThePBone** [comment]
Run `export MAKEFLAGS='-j8'` before installation to enable multi-threaded compilation with 8 threads. It will significantly speed up the compilation (if your CPU can handle that).

Otherwise, I just released a precompiled flatpak package for the Pipewire version, however, it isn't well-tested yet: https://flathub.org/apps/me.timschneeberger.jdsp4linux

**Comment by medmedin2014** [comment]
@ThePBone Thanks, I hate Flatpak, I will instead search how to convert .deb files to Appimage.

**Comment by medmedin2014** [comment]
@ThePBone Is there any official instructions on how to build an appimage for this app ?

**Comment by ThePBone** [comment]
I don't know how to package AppImages and can't provide support for any additional installation methods. AppImage has resources about converting existing binary packages though: https://docs.appimage.org/packaging-guide/converting-binary-packages/index.html
Also, for Arch Linux, [Chaotic-AUR](https://aur.chaotic.cx/) contains (unofficial) precompiled packages of the AUR packages.
