### ISSUE TITLE
AutoEQ Github API rate limit

### ISSUE THREAD

**Issue by Jakeler** [Audio4Linux/JDSP4Linux#17]
Hi, 
thanks for the project, it is really useful, especially direct access to the AutoEQ database is a great feature.

I just noticed that on every click on a search item it makes a new request to the Github API, which has this rate limits of 60 req/h. That is reached fast, when looking at a few headphones and switching back and forth.

So I could think of 2 solutions: 

- Either add a Github login (OAuth) option, that would increase the rate limit to 5000 req/h, then it would allow > 1 req/sec and should be easily enough for any reasonable usage.

- Or (preferably) clone the AutoEQ repo one time into local `~/.cache` and just refresh every few days or with an option in the settings. That would completely circumvent any rate limiting. Also would have the advantage that it even works on systems which are not always connected to the internet.

**Comment by ThePBone** [comment]
Hey,

I didn't consider adding an OAuth login because it would look shady as read-only access should never require a personal account login.

> Or (preferably) clone the AutoEQ repo one time into local ~/.cache and just refresh every few days or with an option in the settings.

This would be a great solution; however, the AutoEQ repo is quite big (845MB; and compressed 341MB). It would not be a good experience for users with slow network speeds or low disk space, especially if they just want to retrieve a single item. In that case, it would be faster to download the data manually, which would defeat the purpose of this integration.

Still, the current AutoEQ integration is not great and pretty slow in general. So I'm planning to do something along these lines:
* Set up a proper REST API for fast access and scrape the AutoEQ repo every 24h into a proper SQL database on my server, instead of parsing the massive [INDEX.md](https://github.com/jaakkopasanen/AutoEq/blob/master/results/INDEX.md) after each search query (like I'm doing at the moment)
* And maybe (as an optional feature) allow users to toggle an 'offline mode' and just dump the whole repo on the disk as you described. It would also be a good backup if my server were down

**Comment by Jakeler** [comment]
Ok, I did not expect the AutoEQ repo to be that big. I have looked through it and think there is a lot of redundant and unnecessary data for this application though. Most important part are the actual GraphicEQ settings, if they are extracted like this:
```
find -name "*GraphicEQ.txt" -exec mkdir -p out/EQ/{} \; -exec cp {} out/EQ/{} \;
```
It is only 22MB or 2MB gzip compressed, so that should be no problem. The repo already includes a zip (without compression) [here](https://github.com/jaakkopasanen/AutoEq/blob/master/results/hesuvi.zip), having only one version per headphone, that makes it even smaller at around 1MB with gzip.

In addition there are `*.png` graphs, overall size of 250MB and not really compressible. I think this could be a optional download or generally fetched on demand. Technically it is just the image form of the `.csv` data, maybe the software could render this itself, would be also better UX to have this integrated with the dark themes, being able to zoom in, hide lines, etc... The csv data is overall 160MB or around 50MB with gzip.

I don't really see the advantage of running a full fledged SQL server, as this needs more resources and adds latency. I would just do it like most Linux package mangers, which first load metadata (package data) into a local database (<100KB in this case). That makes searching basically instant, other data can be loaded on demand and cached as well. Any static file hosting (even Github pages) should be suitable. Or do you see other reasons to have SQL?

**Comment by ThePBone** [comment]
> It is only 22MB or 2MB gzip compressed

Never mind then, I didn't realize there was so much unrelated data there. 
I considered the self-hosted API option because I already have the necessary server infrastructure available because of other projects, but in this case, it isn't a good solution. 

Then I'll probably use a GitHub repo with a GitHub Actions workflow for automation that prepares up-to-date archives.

> Technically it is just the image form of the .csv data, maybe the software could render this itself

Yeah, this is the better alternative. Large pictures are hard to resize inside dynamic layouts anyways, and I already have code for interactive graph widgets lying around, so that won't be an issue.

A 2MB + 50MB download seems reasonable, and if I still end up making the CSV stuff optional, I can fall back to the GraphicEQ.txt data to render a simple frequency response curve.

**Comment by ThePBone** [comment]
This took longer than I expected; I had to rewrite that whole thing because the old implementation was done really dirty and quickly, but it should work much more smoothly now.

![image](https://user-images.githubusercontent.com/38386967/145697075-546b8e45-0b2e-41d5-b222-cd40d87b05a8.png)

Use the `jamesdsp-git` package from the AUR or compile it manually to test it out.

You can interact with the plot using the following methods:
* Scroll/drag = Zoom/move viewport
* Hover over x- or y-axis and scroll = zoom respective axis only
* Click on legend = show/hide specific plots
* Right-click legend = move the legend to another corner
* Regular mouse hover = display tooltip with coordinates under the cursor

Also, there is currently a problem with the data from AutoEq:
All measurements from the 'Crinacle' source lack the CSV file for some reason. If the CSV file is unavailable, the app will fall back to using the GraphicEQ data instead. I've already opened an issue in the AutoEq repo about this.

**Comment by Jakeler** [comment]
Awesome that you immediately worked on the implementation! Yeah, it is much nicer now!

Data location is `~/.config/jamesdsp/autoeq/` currently, which is not right, as these are not configs that should be edited. I would go for either `~/.cache/jamesdsp/autoeq/` ($XDG_CACHE_HOME) for non-essential data or `~/.local/share/jamesdsp/autoeq/` ($XDG_DATA_HOME) for normal application data.
If we are really strict about the [XDG basedir spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) then `graphiceq.conf` would  fit better in  `~/.local/state/` ($XDG_STATE_HOME) instead.

It is also still very white, at least compared to my theme :)
![grafik](https://user-images.githubusercontent.com/13378765/145709379-84e16096-ac58-48d7-95ff-dd5251e1fc79.png)
Would be nice if you could apply the background color, invert font colors etc. there as well.

The interactive plot works very well overall. In addition it would be convenient to have a method that hides all plots besides the one selected, maybe with a double click.

**Comment by ThePBone** [comment]
> go for either ~/.cache/jamesdsp/autoeq/ 

Sure, the path is now set to `~/.cache/jamesdsp/autoeq/ `. 
To migrate:
```
mkdir -p ~/.config/jamesdsp && mv ~/.config/jamesdsp/autoeq/ ~/.cache/jamesdsp
```
> In addition it would be convenient to have a method that hides all plots besides the one selected, maybe with a double click.

Alright, added this as well (commit 885a8c96b6cd033b0a7af53bf185eedf1fe2a86f)

> Would be nice if you could apply the background color, invert font colors etc. there as well.

I'll look into that

**Comment by ThePBone** [comment]
> Would be nice if you could apply the background color, invert font colors etc. there as well.

I've ended up implementing a simple dark mode for the plot.
I can't easily let it inherit the color palette because I would need to determine the plots' colors dynamically which is too much work if I don't want it to look awful.
(the foreground colors might bleed in with the background color depending on which custom color palette is set, so I settled with the regular dark mode switch) 

It is currently not coupled to the theme settings, you can enable it here: `AutoEQ database... > Manage database > Dark mode`
