### ISSUE TITLE
Not able to launch application on linux mint 20.3

### ISSUE THREAD

**Issue by pinbuck** [Audio4Linux/JDSP4Linux#29]
Application installs from repo or deb just fine, but simply doesn't launch.

/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /usr/bin/jamesdsp)

my friend who's on arch said that debian's repositories are years out of date and that I'd have to build qt5base from source to get the latest. am I in the wrong for trying?

I looked at the last issue post which mentions Qt_5.15, however after multiple restarts, update/upgrade, relaunching, command line (how i discovered the qt_5.15 error) I was not able to get past.

**Comment by b1scu1t** [comment]
What is your distro?

**Comment by pinbuck** [comment]
> What is your distro? Which version of Debian?

Linux Mint 20.3 una (as listed in title), and is based on Ubuntu 20.03.

**Comment by ThePBone** [comment]
The `jamesdsp-pipewire` package is only intended for Ubuntu 21.04 and later.

This is because the package repos for Ubuntu 20.04 only include Pipewire version 0.2; a really old release that causes crashes and all kinds of issues with JDSP.

It seems that I forgot to add the special version requirements for the dependencies to the package; normally, APT should detect incompatibility with the dependencies,

You have these options:

a) Use `jamesdsp-pulse` with PulseAudio; it supports Ubuntu 20.04
b) Update your system to Ubuntu 21.04 or later to use the precompiled `jamesdsp-pipewire` package
c)  Compile this application AND pipewire version >0.3 from sources and link their program libraries together manually (not really recommended; compiling Qt manually is not needed in this case)

**Comment by pinbuck** [comment]
![2](https://user-images.githubusercontent.com/96911866/174959324-3880125a-454d-422d-99fa-0d5ba83222c0.png)
Success, binary from source.
