### ISSUE TITLE
compiling release tgz

### ISSUE THREAD

**Issue by raspo666** [Audio4Linux/JDSP4Linux#35]
cloning from git and compiling works fine.
compiling from the v2.3.tar.gz yields:

../../src/data/EelParser.h:4:10: fatal error: model/codecontainer.h: No such file or directory
    4 | #include <model/codecontainer.h>
I was writing a Slackbuild, thats why i fetched the 2.3 release....

**Comment by ThePBone** [comment]
This repository depends on several external GitHub repositories embedded as git submodules. These are not included with the .tar.gz download. 

I recommend using `git` to checkout the v2.3 tag recursively instead:
```
git clone --recursive --branch 2.3 https://github.com/Audio4Linux/JDSP4Linux
```
Otherwise, you'd need to also download a .tar.gz of every repository defined here: https://github.com/Audio4Linux/JDSP4Linux/blob/master/.gitmodules and place it into the correct subdirectory.
