### ISSUE TITLE
Compiling fails

### ISSUE THREAD

**Issue by swimintospace** [Audio4Linux/JDSP4Linux#50]
When I tried to compile with "make -j4" I keep running into this error:
```
In file included from ../../src/audio/pipewire/FilterContainer.h:24,
                 from ../../src/audio/pipewire/FilterContainer.cpp:20:
../../src/audio/pipewire/PwBasePlugin.h:27:10: fatal error: ranges: No such file or directory
   27 | #include <ranges>
      |          ^~~~~~~~
compilation terminated.
make[1]: *** [Makefile:2841: FilterContainer.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/swim/Downloads/JDSP4Linux/build/src'
```

**Comment by ThePBone** [comment]
The compiler can't find the `ranges` feature from libstdc++ that has been added with the new C++20 standard. 

You need to get a newer version of the gcc/g++ compiler that supports the [C++20 standard](https://en.cppreference.com/w/cpp/compiler_support#cpp20) and use it for compilation.

gcc/g++ version 9.4 and later should work.

**Comment by swimintospace** [comment]
I made sure I had the latest version of g++ (9.4.0) and I still run into this error. Not exactly sure why. I made sure to run the compiling multiple times and reinstalled the packages multiple times as well. Might just be an issue with my system then?

**Comment by ThePBone** [comment]
That's weird; the GitHub actions workflow that compiles this app automatically also uses gcc 9.4.0 (on Ubuntu 20.04) without any issues.
Maybe there are multiple compilers installed on your system, so you might need to select gcc 9.4.0 manually: https://forum.qt.io/topic/95073/qmake-uses-wrong-gcc-version-how-to-change-gcc-version-used/2

Either way, I looked through the code, and those headers are unused anyway, Probably because I forgot to remove them after rewriting some of the code. I don't think I have any other references to C++20 features, but feel free to send the compiler log if it complains about different parts of the source.

I've pushed new commits; it should hopefully compile now.

**Comment by swimintospace** [comment]
I fixed it actually by switching my compiler to gcc version 10. After researching, the ranges library is still not in version 9. The app launched as well. Thank you so much for helping!

**Comment by swimintospace** [comment]
I actually had another question if you didn't mind... Would I be able to use configurations from REW software through this software?
Here's an example:
[Logitech_z623.txt](https://github.com/Audio4Linux/JDSP4Linux/files/8647882/Logitech_z623.txt)

**Comment by ThePBone** [comment]
Yes, that's possible, but you need to use an external program to convert them first.

The attached file contains data for a parametric equalizer with peaking filters (same format as EqualizerAPO and AutoEQ). 
You can use this tool: https://github.com/ThePBone/DDCToolbox to convert it into the .VDC file format, which can then be loaded by jamesdsp.
1. Select 'Project > Import > AutoEQ (ParametricEQ.txt)' 
2. Make sure to choose 'All files' instead of 'AutoEQ ParametricEQ.txt' in the file selection dialog and select your file
If it was able to parse the file, it populates the table and plot with the data from REW;
![image](https://user-images.githubusercontent.com/38386967/167318847-50154f21-0e54-4cf7-a901-55dba5aef8b4.png)
 
3. Select 'Project > Export > VDC file' to save it
4. Load the file in the DDC tab in jamesdsp

Here's your sample file converted: [Logitech_z623.vdc.zip](https://github.com/Audio4Linux/JDSP4Linux/files/8647911/Logitech_z623.vdc.zip) (zipped because GitHub blocks unknown filetypes for attachments)

**Comment by swimintospace** [comment]
It worked thank you! Thank you so much for you help. Your project is a lifesaver, easy effects kept crashing on me so now I switched to this.
