### ISSUE TITLE
No output audio unless I add the app to the blocklist

### ISSUE THREAD

**Issue by netiul** [Audio4Linux/JDSP4Linux#53]
Not sure if I overlook something, but there's no audio at all unless I blocklist the app (which probably means it bypasses JamesDSP completely).

Using Ubuntu 21.10 and PipeWire audio server.

I'm using an external audio interface (UMC204HD) and it is the configured as the systems default output audio device. But also when manually selecting in the JamesDSP settings, there is no output.

Any suggestions?

**Comment by Tomoms** [comment]
This has started to happen to me all of a sudden today. Until yesterday, JDSP4Linux was working perfectly. Self-compiled on openSUSE Tumbleweed + Pipewire. I have also pulled the latest sources and recompiled, but in vain.
Log available here: https://susepaste.org/569ff0ca
Any way I can help further debug this problem?

**Comment by ThePBone** [comment]
I recently ran into the same issue and noticed that the virtual "JamesDSP sink" audio device was muted for some reason on my computer.

This is the structure of the audio pipeline:
![Audio pipeline](https://user-images.githubusercontent.com/38386967/188106201-31de2df2-9094-4f7c-8317-f9400c621844.png)

The highlighted sink was muted. I used KDE's audio system settings to unmute the virtual sink device manually. You also can use `pavucontrol` to do this (note that some tools don't show virtual audio devices by default).

If you add an app to the blocklist, it will directly connect to your actual output device rather than the virtual device, so you will still get audio output in that case.

If you still run into the same issue, feel free to reopen.
