### ISSUE TITLE
Random crashes on Arch Linux with Linux Kernel 5.18.10-zen

### ISSUE THREAD

**Issue by ilchub** [Audio4Linux/JDSP4Linux#62]
JamesDSP is accidentally crashing with the following log in the stdout:

```
QFSFileEngine::open: No file name specified
[23:22:12.210] [ERR] DspHost::refreshLiveprog: Cannot open file path. Disabling liveprog.
QIODevice::read (QFile, ""): device not open
[23:22:12.210] [DBG] DspHost::refreshLiveprog: @init section not found
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
[23:22:12.366] [DBG] AssetManager::extractGroup: 5 assets extracted (type 0)
[23:22:12.366] [DBG] AssetManager::extractGroup: 3 assets extracted (type 1)
[23:22:12.611] [INF] MainWindow::ctor: UI initialized
[23:22:12.634] [DBG] AppConfig::isAppBlocked("Firefox") -> false
[23:22:12.634] [DBG] PipewireAudioService: new default output device: alsa_output.usb-FIFINE_Microphones_FIFINE_K678_Microphone_REV1.0-00.analog-stereo
[23:22:12.635] [DBG] PwPipelineManager: new metadata property: 91, target.node, Spa:Id, 31
[23:22:16.972] [DBG] PwPipelineManager: Stream/Output/Audio Firefox was removed
[23:22:16.986] [DBG] PwPipelineManager: Stream/Output/Audio 91 Firefox was added
[23:22:16.988] [DBG] AppConfig::isAppBlocked("Firefox") -> false
[23:22:16.989] [DBG] PwPipelineManager: new metadata property: 91, target.node, Spa:Id, 31
[23:22:16.994] [DBG] PwPipelineManager: Firefox port 109 is connected to jamesdsp_sink port 52
[23:22:16.994] [DBG] PwPipelineManager: Firefox port 107 is connected to jamesdsp_sink port 32
Caught SIGSEGV (11)
Collecting infomation about the crash...
Done! Crash report saved to /tmp/jamesdsp/crash.dmp.

Consider to launch this application with the parameter '--spinlock-on-crash' to wait for a debugger in case of a crash.
```

System is using PipeWire. Here is an output of ```pw-cli dump short core```
```
0: u="myuser" h="dell-inspiron74052n1" v="0.3.54" n="pipewire-0"
```
System Kernel is:
```
Linux dell-inspiron74052n1 5.18.10-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 07 Jul 2022 17:18:11 +0000 x86_64 GNU/Linux
```

Please refer to the crash dump attached below.
[crash.txt](https://github.com/Audio4Linux/JDSP4Linux/files/9087360/crash.txt)

Feel free to ask for any additional debug information.

Best Regards.

**Comment by lvetritti** [comment]
I'm facing the same random crashes than you on Fedora 36 and the crash dump has the same backtrace.

Crash dump:

Caught SIGSEGV (11) in ???
Fault at memory location 0x0 due to address not mapped to object (1).
Thread 11434: jamesdsp
=== Context:
R8:f95a8040 R9:800 R10:f401d038 R11:0 R12:f95b1040 R13:f95a8040 R14:fa12c040
R15:0 RDI:fffffc00 RSI:0 RBP:f95ef010 RBX:800 RDX:e8004b80 RAX:0 RCX:e8002b80
RSP:f99e6840 RIP:6f023b EFL:10246 CSGSFS:33 ERR:4 TRAPNO:e OLDMASK:0 CR2:0
=== Binary:
Compile date: Dec 31 2021 00:00:00
GNU version: 110201
=== Backtrace:
/usr/bin/jamesdsp[400000](+1e5767)[5e5767]
/lib64/libc.so.6[22800000](+3ea70)[2283ea70]
/usr/bin/jamesdsp[400000](+2f023b)[6f023b]
/usr/bin/jamesdsp[400000](+147a16)[547a16]
/lib64/libpipewire-0.3.so.0[246e1000](+52f49)[24733f49]
/lib64/libpipewire-0.3.so.0[246e1000](+61669)[24742669]
/lib64/libpipewire-0.3.so.0[246e1000](+64cac)[24745cac]
/usr/lib64/spa-0.2/support/libspa-support.so[f9cdc000](+749d)[f9ce349d]
/lib64/libpipewire-0.3.so.0[246e1000](+42457)[24723457]
/lib64/libc.so.6[22800000](+8ce2d)[2288ce2d]
/lib64/libc.so.6[22800000](+112620)[22912620]
=== Code:
6f01fb:  00 00 48 8b bd 30 7c 1f 00 48 29 df e8 14 f4 ff ff 48 3d 80 00 00 00 76
6f0213:  07 48 89 9d 30 7c 1f 00 48 85 db 74 2f 48 8b 8d 48 7c 1f 00 48 8b 95 50
6f022b:  7c 1f 00 31 c0 f3 41 0f 10 04 86 f3 0f 11 04 81>f3 41 0f 10 04 87 f3 0f
6f0243:  11 04 82 48 83 c0 01 48 39 c3 75 e1 80 7d 00 00 48 89 de 48 89 ef 74 65
6f025b:  e8 10 f9 ff ff 48 89 ef 89 c6 49 89 f6 e8 43 f1 ff ff 48 89 da 44 89 f6
6f0273:  48 89 ef e8 95 f9 ff ff
=== Local backtrace:
Offset cannot be resolved: No offset present?
Offset cannot be resolved: No offset present?
Offset cannot be resolved: No offset present?
0x0000000000052f49: ?? ??:0
0x0000000000061669: ?? ??:0
0x0000000000064cac: ?? ??:0
0x000000000000749d: ?? ??:0
0x0000000000042457: ?? ??:0
0x000000000008ce2d: ?? ??:0
0x0000000000112620: ?? ??:0
=== System:
Linux version 5.18.13-200.fc36.x86_64 (mockbuild@bkernel01.iad2.fedoraproject.org) (gcc (GCC) 12.1.1 20220507 (Red Hat 12.1.1-1), GNU ld version 2.37-27.fc36) #1 SMP PREEMPT_DYNAMIC Fri Jul 22 14:03:36 UTC 2022
7eb327cedf1c4bcabccaa8f3ea9744fd
LSB Version:    :core-4.1-amd64:core-4.1-ia32:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-ia32:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-ia32:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 36 (Thirty Six)
Release:        36
Codename:       ThirtySix

**Comment by MNS26** [comment]
ive been looking at other reports of crashes and basically all show audio being played by firefox 🤔

**Comment by ThePBone** [comment]
> ive been looking at other reports of crashes and basically all show audio being played by firefox 

Good catch, I didn't notice that. I'll keep firefox running for a while, maybe this happens on my machine too.

Also, could someone please [compile this app manually](https://github.com/Audio4Linux/JDSP4Linux#build-from-sources), try to wait for another crash, and post the dump here? The binaries built from the AUR have stripped all their debug information, so the crash dumps lack some important information.

**Comment by goosesima** [comment]
> Also, could someone please [compile this app manually](https://github.com/Audio4Linux/JDSP4Linux#build-from-sources), try to wait for another crash, and post the dump here? The binaries built from the AUR have stripped all their debug information, so the crash dumps lack some important information.
I don't have crashes with compiled jamesdsp from git.

**Comment by ThePBone** [comment]
Release v2.4 includes the fix for this issue: https://github.com/Audio4Linux/JDSP4Linux/releases/tag/2.4
